<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>Machine Learning - 2301CS621</b></center>

<center><b><h1>Lab - 2</b></center>    
<pre>



### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 3. Assign it to a variable called users and use the 'user_id' as index

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

In [5]:
df = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user",sep="|")
df
# print(df.to_string())

# print(pd.options.display.max_rows)
# df.describe()

     user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]

### Step 4. See the first 25 entries

In [4]:
df.head(25)

    user_id  age gender     occupation zip_code
0         1   24      M     technician    85711
1         2   53      F          other    94043
2         3   23      M         writer    32067
3         4   24      M     technician    43537
4         5   33      F          other    15213
5         6   42      M      executive    98101
6         7   57      M  administrator    91344
7         8   36      M  administrator    05201
8         9   29      M        student    01002
9        10   53      M         lawyer    90703
10       11   39      F          other    30329
11       12   28      F          other    06405
12       13   47      M       educator    29206
13       14   45      M      scientist    55106
14       15   49      F       educator    97301
15       16   21      M  entertainment    10309
16       17   30      M     programmer    06355
17       18   35      F          other    37212
18       19   40      M      librarian    02138
19       20   42      F      homemaker    95660
20       21   26      M         writer    30068
21       22   25      M         writer    40206
22       23   30      F         artist    48197
23       24   21      F         artist    94533
24       25   39      M       engineer    55107

### Step 5. See the last 10 entries

In [4]:
df.tail(10)

     user_id  age gender     occupation zip_code
933      934   61      M       engineer    22902
934      935   42      M         doctor    66221
935      936   24      M          other    32789
936      937   48      M       educator    98072
937      938   38      F     technician    55038
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

### Step 6. What is the number of observations in the dataset?

In [10]:
df.shape # (943, 5)

# df.shape[0] # Row
# df.shape[1] # Column

(943, 5)

### Step 7. What is the number of columns in the dataset?

In [13]:
# df.shape[1]
# OR
df.columns # Return to Object

Index(['user_id', 'age', 'gender', 'occupation', 'zip_code'], dtype='object')

### Step 8. Print the name of all the columns.

In [14]:
df.columns

Index(['user_id', 'age', 'gender', 'occupation', 'zip_code'], dtype='object')

### Step 9. How is the dataset indexed?

In [15]:
df.index

RangeIndex(start=0, stop=943, step=1)

### Step 10. What is the data type of each column?

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 943 entries, 0 to 942
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user_id     943 non-null    int64
 1   age         943 non-null    int64
 2   gender      943 non-null    object
 3   occupation  943 non-null    object
 4   zip_code    943 non-null    object
dtypes: int64(2), object(3)
memory usage: 37.0+ KB

### Step 11. Print only the occupation column

In [17]:
df['occupation']

0         technician
1              other
2             writer
3         technician
4              other
           ...
938          student
939    administrator
940          student
941        librarian
942          student
Name: occupation, Length: 943, dtype: object

### Step 12. How many different occupations are in this dataset?

In [18]:
df['occupation'].nunique()

21

### Step 13. What is the most frequent occupation?

In [12]:
df['occupation'].value_counts()

occupation
student          196
other            105
educator          95
administrator     79
engineer          67
programmer        66
librarian         51
writer            45
executive         32
scientist         31
artist            28
technician        27
marketing         26
entertainment     18
healthcare        16
retired           14
lawyer            12
salesman          12
none               9
homemaker          7
doctor             7
Name: count, dtype: int64

### Step 14. Summarize the DataFrame.

In [109]:
df.describe()

          user_id         age
count  943.000000  943.000000
mean   472.000000   34.051962
std    272.364951   12.192740
min      1.000000    7.000000
25%    236.500000   25.000000
50%    472.000000   31.000000
75%    707.500000   43.000000
max    943.000000   73.000000

### Step 15. Summarize all the columns

In [110]:
df.describe(include='all')

           user_id         age gender occupation zip_code
count   943.000000  943.000000    943        943      943
unique         NaN         NaN      2         21      795
top            NaN         NaN      M    student    55414
freq           NaN         NaN    670        196        9
mean    472.000000   34.051962    NaN        NaN      NaN
std     272.364951   12.192740    NaN        NaN      NaN
min       1.000000    7.000000    NaN        NaN      NaN
25%     236.500000   25.000000    NaN        NaN      NaN
50%     472.000000   31.000000    NaN        NaN      NaN
75%     707.500000   43.000000    NaN        NaN      NaN
max     943.000000   73.000000    NaN        NaN      NaN

### Step 16. Summarize only the occupation column

In [112]:
df['occupation'].value_counts()

occupation
student          196
other            105
educator          95
administrator     79
engineer          67
programmer        66
librarian         51
writer            45
executive         32
scientist         31
artist            28
technician        27
marketing         26
entertainment     18
healthcare        16
retired           14
lawyer            12
salesman          12
none               9
homemaker          7
doctor             7
Name: count, dtype: int64

### Step 17. What is the mean age of users?

In [113]:
mean_age = df['age'].mean()
print(mean_age)

34.05196182396607

### Step 18. What is the age with least occurrence?

In [114]:
least_common_age = df['age'].value_counts().idxmin()
print(least_common_age)

7

## Part -2

- **All tasks** are based on the **single dataset** loaded in the Setup cell below.

In [6]:
import pandas as pd
import numpy as np

np.random.seed(42)
n = 200

cities    = ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix',
             'Philadelphia', 'San Antonio', 'Dallas', 'Austin', 'Seattle']
regions   = {'New York': 'East', 'Los Angeles': 'West', 'Chicago': 'North',
             'Houston': 'South', 'Phoenix': 'West', 'Philadelphia': 'East',
             'San Antonio': 'South', 'Dallas': 'South', 'Austin': 'South', 'Seattle': 'West'}
categories = ['Electronics', 'Clothing', 'Food', 'Furniture']
products   = {
    'Electronics': ['Laptop', 'Smartphone', 'Headphones', 'Tablet', 'Camera'],
    'Clothing':    ['T-Shirt', 'Jeans', 'Jacket', 'Sneakers', 'Dress'],
    'Food':        ['Coffee Beans', 'Olive Oil', 'Pasta', 'Chocolate', 'Tea'],
    'Furniture':   ['Office Chair', 'Desk', 'Bookshelf', 'Sofa', 'Lamp']
}
prices     = {
    'Laptop': 999.99, 'Smartphone': 799.99, 'Headphones': 199.99,
    'Tablet': 499.99, 'Camera': 649.99, 'T-Shirt': 29.99,
    'Jeans': 59.99, 'Jacket': 89.99, 'Sneakers': 79.99, 'Dress': 69.99,
    'Coffee Beans': 14.99, 'Olive Oil': 12.99, 'Pasta': 5.99,
    'Chocolate': 8.99, 'Tea': 9.99, 'Office Chair': 249.99,
    'Desk': 349.99, 'Bookshelf': 149.99, 'Sofa': 799.99, 'Lamp': 49.99
}
salespersons = ['Alice Johnson', 'Bob Martinez', 'Carol White',
                'David Lee', 'Emma Davis']
first_names  = ['James', 'Mary', 'John', 'Patricia', 'Robert', 'Jennifer',
                'Michael', 'Linda', 'William', 'Barbara', 'David', 'Susan',
                'Richard', 'Jessica', 'Thomas', 'Sarah', 'Charles', 'Karen',
                'Daniel', 'Lisa']
last_names   = ['Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Garcia',
                'Miller', 'Davis', 'Wilson', 'Moore', 'Taylor', 'Anderson',
                'Thomas', 'Jackson', 'White', 'Harris', 'Martin', 'Thompson',
                'Young', 'Robinson']

city_list    = np.random.choice(cities, n)
cat_list     = np.random.choice(categories, n)
prod_list    = [np.random.choice(products[c]) for c in cat_list]
price_list   = np.array([prices[p] for p in prod_list])
disc_list    = np.random.choice([0, 5, 10, 15, 20, 25, 30], n)
qty_list     = np.random.randint(1, 11, n)
rating_list  = np.random.choice([1, 2, 3, 4, 5], n, p=[0.05, 0.10, 0.20, 0.40, 0.25])
dates        = pd.date_range(start='2023-01-01', end='2023-12-31', periods=n)
dates        = pd.to_datetime(np.sort(np.random.choice(dates, n, replace=False)))
cust_names   = [f"{np.random.choice(first_names)} {np.random.choice(last_names)}" for _ in range(n)]

# Introduce some missing values
rating_arr = rating_list.astype(float)
rating_arr[np.random.choice(n, 12, replace=False)] = np.nan
disc_arr = disc_list.astype(float)
disc_arr[np.random.choice(n, 8, replace=False)] = np.nan

df = pd.DataFrame({
    'order_id':      [f'ORD-{1000+i}' for i in range(n)],
    'order_date':    dates,
    'customer_name': cust_names,
    'city':          city_list,
    'region':        [regions[c] for c in city_list],
    'category':      cat_list,
    'product':       prod_list,
    'quantity':      qty_list,
    'unit_price':    price_list,
    'discount':      disc_arr,
    'salesperson':   np.random.choice(salespersons, n),
    'rating':        rating_arr
})

# Add duplicate rows intentionally
df = pd.concat([df, df.iloc[[5, 23, 77]]], ignore_index=True)


df.head()

,order_id,order_date,customer_name,city,region,category,product,quantity,unit_price,discount,salesperson,rating
0,ORD-1000,2023-01-01 00:00:00.000000000,Karen Robinson,San Antonio,South,Clothing,Jacket,1,89.99,10.0,David Lee,5.0
1,ORD-1001,2023-01-02 19:53:58.190954773,Michael Williams,Houston,South,Food,Olive Oil,5,12.99,15.0,David Lee,4.0
2,ORD-1002,2023-01-04 15:47:56.381909547,Karen Moore,Dallas,South,Food,Olive Oil,7,12.99,0.0,Bob Martinez,NaN
3,ORD-1003,2023-01-06 11:41:54.572864321,Michael Martin,Phoenix,West,Furniture,Desk,6,349.99,15.0,David Lee,5.0
4,ORD-1004,2023-01-08 07:35:52.763819095,Jessica Williams,San Antonio,South,Furniture,Office Chair,1,249.99,10.0,Emma Davis,4.0

### ✅ Task 1 — First Inspection
Perform a basic inspection of the DataFrame `df`:
1. Display the **first 8 rows**.
2. Display the **last 5 rows**.
3. Print the **shape** (rows, columns).
4. Print all **column names**.

In [7]:
# 1
df.head(8)

,order_id,order_date,customer_name,city,region,category,product,quantity,unit_price,discount,salesperson,rating
0,ORD-1000,2023-01-01 00:00:00.000000000,Karen Robinson,San Antonio,South,Clothing,Jacket,1,89.99,10.0,David Lee,5.0
1,ORD-1001,2023-01-02 19:53:58.190954773,Michael Williams,Houston,South,Food,Olive Oil,5,12.99,15.0,David Lee,4.0
2,ORD-1002,2023-01-04 15:47:56.381909547,Karen Moore,Dallas,South,Food,Olive Oil,7,12.99,0.0,Bob Martinez,NaN
3,ORD-1003,2023-01-06 11:41:54.572864321,Michael Martin,Phoenix,West,Furniture,Desk,6,349.99,15.0,David Lee,5.0
4,ORD-1004,2023-01-08 07:35:52.763819095,Jessica Williams,San Antonio,South,Furniture,Office Chair,1,249.99,10.0,Emma Davis,4.0
5,ORD-1005,2023-01-10 03:29:50.954773869,Susan Thomas,Seattle,West,Electronics,Laptop,5,999.99,20.0,Emma Davis,4.0
6,ORD-1006,2023-01-11 23:23:49.145728643,Mary Williams,Chicago,North,Electronics,Laptop,5,999.99,15.0,Emma Davis,NaN
7,ORD-1007,2023-01-13 19:17:47.336683417,Robert Taylor,San Antonio,South,Furniture,Bookshelf,6,149.99,20.0,Alice Johnson,5.0

In [8]:
# 2
df.tail(5)

,order_id,order_date,customer_name,city,region,category,product,quantity,unit_price,discount,salesperson,rating
198,ORD-1198,2023-12-29 04:06:01.809045228,Robert Brown,Los Angeles,West,Food,Tea,4,9.99,0.0,Alice Johnson,4.0
199,ORD-1199,2023-12-31 00:00:00.000000000,Susan Robinson,Philadelphia,East,Clothing,Dress,6,69.99,10.0,Bob Martinez,NaN
200,ORD-1005,2023-01-10 03:29:50.954773869,Susan Thomas,Seattle,West,Electronics,Laptop,5,999.99,20.0,Emma Davis,4.0
201,ORD-1023,2023-02-12 01:41:18.391959799,Michael Robinson,Philadelphia,East,Furniture,Bookshelf,1,149.99,10.0,Emma Davis,NaN
202,ORD-1077,2023-05-21 20:15:40.703517588,Sarah Davis,Austin,South,Food,Tea,2,9.99,5.0,Bob Martinez,4.0

In [9]:
# 3
df.shape

(203, 12)

In [10]:
# 4
df.columns

Index(['order_id', 'order_date', 'customer_name', 'city', 'region', 'category',
       'product', 'quantity', 'unit_price', 'discount', 'salesperson',
       'rating'],
      dtype='object')

### ✅ Task 2 — Data Types & Info
1. Display the **data type** of each column using `.dtypes`.
2. Use `.info()` to get a full summary.
3. Identify which columns have **missing values** and how many.

In [11]:
# 2.1
df.head(8)

,order_id,order_date,customer_name,city,region,category,product,quantity,unit_price,discount,salesperson,rating
0,ORD-1000,2023-01-01 00:00:00.000000000,Karen Robinson,San Antonio,South,Clothing,Jacket,1,89.99,10.0,David Lee,5.0
1,ORD-1001,2023-01-02 19:53:58.190954773,Michael Williams,Houston,South,Food,Olive Oil,5,12.99,15.0,David Lee,4.0
2,ORD-1002,2023-01-04 15:47:56.381909547,Karen Moore,Dallas,South,Food,Olive Oil,7,12.99,0.0,Bob Martinez,NaN
3,ORD-1003,2023-01-06 11:41:54.572864321,Michael Martin,Phoenix,West,Furniture,Desk,6,349.99,15.0,David Lee,5.0
4,ORD-1004,2023-01-08 07:35:52.763819095,Jessica Williams,San Antonio,South,Furniture,Office Chair,1,249.99,10.0,Emma Davis,4.0
5,ORD-1005,2023-01-10 03:29:50.954773869,Susan Thomas,Seattle,West,Electronics,Laptop,5,999.99,20.0,Emma Davis,4.0
6,ORD-1006,2023-01-11 23:23:49.145728643,Mary Williams,Chicago,North,Electronics,Laptop,5,999.99,15.0,Emma Davis,NaN
7,ORD-1007,2023-01-13 19:17:47.336683417,Robert Taylor,San Antonio,South,Furniture,Bookshelf,6,149.99,20.0,Alice Johnson,5.0

In [12]:
# 2.2
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203 entries, 0 to 202
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       203 non-null    object
 1   order_date     203 non-null    datetime64[ns]
 2   customer_name  203 non-null    object
 3   city           203 non-null    object
 4   region         203 non-null    object
 5   category       203 non-null    object
 6   product        203 non-null    object
 7   quantity       203 non-null    int32
 8   unit_price     203 non-null    float64
 9   discount       195 non-null    float64
 10  salesperson    203 non-null    object
 11  rating         190 non-null    float64
dtypes: datetime64[ns](1), float64(3), int32(1), object(7)
memory usage: 18.4+ KB

In [13]:
# 2.3
df.isnull().sum()

order_id          0
order_date        0
customer_name     0
city              0
region            0
category          0
product           0
quantity          0
unit_price        0
discount          8
salesperson       0
rating           13
dtype: int64

### ✅ Task 3 — Descriptive Statistics
1. Use `.describe()` to get summary statistics for **all numeric columns**.
2. Use `.describe(include='object')` to get statistics for **text columns**.
3. Print the **mean**, **min**, and **max** of `unit_price` separately.

In [40]:
# # df.describe()
# df.describe(include = 'all')
# df.describe(include = 'object')
print(df['unit_price'].min())
print(df['unit_price'].max())
print(df['unit_price'].mean())

5.99
999.99
274.1033004926108

### ✅ Task 4 — Selecting Columns
1. Select and display only the `customer_name` and `city` columns.
2. Select the columns `product`, `quantity`, `unit_price` and display the **first 10 rows**.
3. Store the `unit_price` column as a **Pandas Series** named `prices_series` and print its type.

In [51]:
print(df[['customer_name', 'city']])

print(df[['product', 'quantity', 'unit_price']].head(10))

prices_series = df['unit_price']
print(type(prices_series))

        customer_name          city
0      Karen Robinson   San Antonio
1    Michael Williams       Houston
2         Karen Moore        Dallas
3      Michael Martin       Phoenix
4    Jessica Williams   San Antonio
..                ...           ...
198      Robert Brown   Los Angeles
199    Susan Robinson  Philadelphia
200      Susan Thomas       Seattle
201  Michael Robinson  Philadelphia
202       Sarah Davis        Austin

[203 rows x 2 columns]
        product  quantity  unit_price
0        Jacket         1       89.99
1     Olive Oil         5       12.99
2     Olive Oil         7       12.99
3          Desk         6      349.99
4  Office Chair         1      249.99
5        Laptop         5      999.99
6        Laptop         5      999.99
7     Bookshelf         6      149.99
8           Tea         3        9.99
9         Jeans         5       59.99
<class 'pandas.core.series.Series'>

### ✅ Task 5 — Filtering Rows
Filter and display:
1. All orders from the **'Electronics'** category.
2. All orders where `quantity` is **greater than 7**.
3. All orders from **'New York'** city.
4. Print the **row count** for each filtered result.

In [48]:
ele = df[df['category'] == 'Electronics']
qua = df[df['quantity'] > 7 ]
new = df[df['city'] == 'New York']

print(ele.shape[0])
print(qua.shape[0])
print(new.shape[0])

48
57
23

### ✅ Task 6 — Sorting
1. Sort the DataFrame by `unit_price` in **descending order** and display the top 10 rows.
2. Sort by `category` (ascending) and then by `unit_price` (descending) — **multi-column sort**.
3. Display the **cheapest 10 products** (by unit_price).

In [52]:
df.sort_values(by='unit_price', ascending = False).head(10)

,order_id,order_date,customer_name,city,region,category,product,quantity,unit_price,discount,salesperson,rating,Clothing,Food,Furniture,Electronics
6,ORD-1006,2023-01-11 23:23:49.145728643,Mary Williams,Chicago,North,Electronics,Laptop,5,999.99,15.0,Emma Davis,NaN,Electronics,Electronics,Electronics,Electronics
5,ORD-1005,2023-01-10 03:29:50.954773869,Susan Thomas,Seattle,West,Electronics,Laptop,5,999.99,20.0,Emma Davis,4.0,Electronics,Electronics,Electronics,Electronics
33,ORD-1033,2023-03-02 08:41:00.301507538,Susan Jones,Chicago,North,Electronics,Laptop,6,999.99,20.0,Alice Johnson,5.0,Electronics,Electronics,Electronics,Electronics
74,ORD-1074,2023-05-16 08:33:46.130653266,Linda Thomas,Dallas,South,Electronics,Laptop,2,999.99,10.0,Bob Martinez,NaN,Electronics,Electronics,Electronics,Electronics
63,ORD-1063,2023-04-26 05:40:06.030150754,David Johnson,Seattle,West,Electronics,Laptop,1,999.99,10.0,Carol White,4.0,Electronics,Electronics,Electronics,Electronics
180,ORD-1180,2023-11-26 05:54:34.371859296,Patricia Garcia,San Antonio,South,Electronics,Laptop,5,999.99,0.0,Bob Martinez,4.0,Electronics,Electronics,Electronics,Electronics
176,ORD-1176,2023-11-18 22:18:41.608040200,Linda Thompson,New York,East,Electronics,Laptop,9,999.99,10.0,David Lee,4.0,Electronics,Electronics,Electronics,Electronics
167,ORD-1167,2023-11-02 11:12:57.889447236,Karen White,Houston,South,Electronics,Laptop,9,999.99,5.0,Emma Davis,3.0,Electronics,Electronics,Electronics,Electronics
200,ORD-1005,2023-01-10 03:29:50.954773869,Susan Thomas,Seattle,West,Electronics,Laptop,5,999.99,20.0,Emma Davis,4.0,Electronics,Electronics,Electronics,Electronics
107,ORD-1107,2023-07-15 17:14:46.432160804,Susan Brown,Dallas,South,Electronics,Laptop,1,999.99,20.0,Carol White,4.0,Electronics,Electronics,Electronics,Electronics

In [53]:
df.sort_values(by=['category', 'unit_price'], ascending = [True, False])

,order_id,order_date,customer_name,city,region,category,product,quantity,unit_price,discount,salesperson,rating,Clothing,Food,Furniture,Electronics
0,ORD-1000,2023-01-01 00:00:00.000000000,Karen Robinson,San Antonio,South,Clothing,Jacket,1,89.99,10.0,David Lee,5.0,Electronics,Electronics,Electronics,Electronics
56,ORD-1056,2023-04-13 10:22:18.693467337,Robert Johnson,Los Angeles,West,Clothing,Jacket,9,89.99,0.0,David Lee,4.0,Electronics,Electronics,Electronics,Electronics
81,ORD-1081,2023-05-29 03:51:33.467336684,Barbara Brown,Austin,South,Clothing,Jacket,7,89.99,15.0,David Lee,4.0,Electronics,Electronics,Electronics,Electronics
124,ORD-1124,2023-08-15 19:32:15.678391960,Sarah Jones,New York,East,Clothing,Jacket,6,89.99,30.0,Carol White,2.0,Electronics,Electronics,Electronics,Electronics
127,ORD-1127,2023-08-21 07:14:10.251256284,John Smith,Phoenix,West,Clothing,Jacket,8,89.99,25.0,David Lee,5.0,Electronics,Electronics,Electronics,Electronics
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,ORD-1109,2023-07-19 09:02:42.814070352,Susan Miller,Chicago,North,Furniture,Lamp,9,49.99,20.0,David Lee,4.0,Electronics,Electronics,Electronics,Electronics
152,ORD-1152,2023-10-06 00:43:25.025125628,Jennifer Wilson,Philadelphia,East,Furniture,Lamp,4,49.99,25.0,Carol White,3.0,Electronics,Electronics,Electronics,Electronics
154,ORD-1154,2023-10-09 16:31:21.407035176,Daniel Wilson,Austin,South,Furniture,Lamp,4,49.99,0.0,Emma Davis,3.0,Electronics,Electronics,Electronics,Electronics
172,ORD-1172,2023-11-11 14:42:48.844221108,William Garcia,Phoenix,West,Furniture,Lamp,2,49.99,5.0,Alice Johnson,5.0,Electronics,Electronics,Electronics,Electronics
183,ORD-1183,2023-12-01 17:36:28.944723620,David Thompson,New York,East,Furniture,Lamp,7,49.99,5.0,Bob Martinez,4.0,Electronics,Electronics,Electronics,Electronics

In [54]:
cheap = df.sort_values(by='unit_price', ascending = True)
print(cheap.head(10))

     order_id                    order_date     customer_name         city  \
123  ORD-1123 2023-08-13 23:38:17.487437188       Susan White  San Antonio
114  ORD-1114 2023-07-28 12:32:33.768844220   Jessica Johnson     New York
196  ORD-1196 2023-12-25 12:18:05.427135680  Michael Anderson      Phoenix
140  ORD-1140 2023-09-14 01:55:46.733668344    Thomas Jackson      Seattle
43   ORD-1043 2023-03-20 15:40:42.211055277       Mary Wilson       Austin
85   ORD-1085 2023-06-05 11:27:26.231155780     Barbara Moore       Dallas
15   ORD-1015 2023-01-28 10:29:32.864321608        John Moore      Phoenix
20   ORD-1020 2023-02-06 13:59:23.819095477  Charles Anderson      Phoenix
113  ORD-1113 2023-07-26 16:38:35.577889448     David Johnson      Chicago
187  ORD-1187 2023-12-09 01:12:21.708542716     Jessica Brown      Seattle

    region category    product  quantity  unit_price  discount    salesperson  \
123  South     Food      Pasta         8        5.99      30.0  Alice Johnson
114   East     Food      Pasta         8        5.99      10.0   Bob Martinez
196   West     Food      Pasta         2        5.99       0.0  Alice Johnson
140   West     Food      Pasta         9        5.99      15.0      David Lee
43   South     Food  Chocolate         5        8.99       5.0  Alice Johnson
85   South     Food  Chocolate         8        8.99       0.0    Carol White
15    West     Food  Chocolate        10        8.99      30.0     Emma Davis
20    West     Food  Chocolate         1        8.99      10.0      David Lee
113  North     Food  Chocolate         6        8.99      15.0    Carol White
187   West     Food  Chocolate         9        8.99      20.0      David Lee

     rating     Clothing         Food    Furniture  Electronics
123     2.0  Electronics  Electronics  Electronics  Electronics
114     4.0  Electronics  Electronics  Electronics  Electronics
196     5.0  Electronics  Electronics  Electronics  Electronics
140     5.0  Electronics  Electronics  Electronics  Electronics
43      4.0  Electronics  Electronics  Electronics  Electronics
85      4.0  Electronics  Electronics  Electronics  Electronics
15      5.0  Electronics  Electronics  Electronics  Electronics
20      4.0  Electronics  Electronics  Electronics  Electronics
113     3.0  Electronics  Electronics  Electronics  Electronics
187     3.0  Electronics  Electronics  Electronics  Electronics

### ✅ Task 7 — Value Counts
1. Count how many orders belong to each **category**.
2. Count how many orders were handled by each **salesperson**.
3. Find the **most common city** in the dataset.
4. Show the distribution of **customer ratings** (including NaN count).

In [61]:
df['category'].value_counts()
df['salesperson'].value_counts()
df['city'].value_counts().idxmax()
df['rating'].value_counts(dropna = False)

rating
4.0    85
5.0    49
3.0    33
2.0    17
NaN    13
1.0     6
Name: count, dtype: int64

### ✅ Task 8 — Adding a New Column
Add a new column called **`total_revenue`** computed as:
> `total_revenue = quantity × unit_price × (1 - discount / 100)`

> ⚠️ Treat missing `discount` values as **0** (no discount).

Print the first 10 rows showing `product`, `quantity`, `unit_price`, `discount`, and `total_revenue`.

In [68]:
df['total_revenue'] = df['quantity'] * df['unit_price'] * ( 1 - df['discount'].fillna(0) / 100)
print(df)

     order_id                    order_date     customer_name          city  \
0    ORD-1000 2023-01-01 00:00:00.000000000    Karen Robinson   San Antonio
1    ORD-1001 2023-01-02 19:53:58.190954773  Michael Williams       Houston
2    ORD-1002 2023-01-04 15:47:56.381909547       Karen Moore        Dallas
3    ORD-1003 2023-01-06 11:41:54.572864321    Michael Martin       Phoenix
4    ORD-1004 2023-01-08 07:35:52.763819095  Jessica Williams   San Antonio
..        ...                           ...               ...           ...
198  ORD-1198 2023-12-29 04:06:01.809045228      Robert Brown   Los Angeles
199  ORD-1199 2023-12-31 00:00:00.000000000    Susan Robinson  Philadelphia
200  ORD-1005 2023-01-10 03:29:50.954773869      Susan Thomas       Seattle
201  ORD-1023 2023-02-12 01:41:18.391959799  Michael Robinson  Philadelphia
202  ORD-1077 2023-05-21 20:15:40.703517588       Sarah Davis        Austin

    region     category       product  quantity  unit_price  discount  \
0    South     Clothing        Jacket         1       89.99      10.0
1    South         Food     Olive Oil         5       12.99      15.0
2    South         Food     Olive Oil         7       12.99       0.0
3     West    Furniture          Desk         6      349.99      15.0
4    South    Furniture  Office Chair         1      249.99      10.0
..     ...          ...           ...       ...         ...       ...
198   West         Food           Tea         4        9.99       0.0
199   East     Clothing         Dress         6       69.99      10.0
200   West  Electronics        Laptop         5      999.99      20.0
201   East    Furniture     Bookshelf         1      149.99      10.0
202  South         Food           Tea         2        9.99       5.0

       salesperson  rating     Clothing         Food    Furniture  \
0        David Lee     5.0  Electronics  Electronics  Electronics
1        David Lee     4.0  Electronics  Electronics  Electronics
2     Bob Martinez     NaN  Electronics  Electronics  Electronics
3        David Lee     5.0  Electronics  Electronics  Electronics
4       Emma Davis     4.0  Electronics  Electronics  Electronics
..             ...     ...          ...          ...          ...
198  Alice Johnson     4.0  Electronics  Electronics  Electronics
199   Bob Martinez     NaN  Electronics  Electronics  Electronics
200     Emma Davis     4.0  Electronics  Electronics  Electronics
201     Emma Davis     NaN  Electronics  Electronics  Electronics
202   Bob Martinez     4.0  Electronics  Electronics  Electronics

     Electronics  revenue  total_revenue
0    Electronics    89.99        80.9910
1    Electronics    64.95        55.2075
2    Electronics    90.93        90.9300
3    Electronics  2099.94      1784.9490
4    Electronics   249.99       224.9910
..           ...      ...            ...
198  Electronics    39.96        39.9600
199  Electronics   419.94       377.9460
200  Electronics  4999.95      3999.9600
201  Electronics   149.99       134.9910
202  Electronics    19.98        18.9810

[203 rows x 18 columns]

### ✅ Task 9 — Handling Missing Values
1. Count the total number of missing values in the **entire DataFrame**.
2. Fill missing `rating` values with the **median** rating.
3. Fill missing `discount` values with **0**.
4. Confirm there are **no more missing values** after filling.

In [14]:
# 1
print(df.isnull().sum().sum())
# 2
med = df['rating'].median()
print(med)
# 3
df['rating'] = df['rating'].fillna(med)
print(df['rating'])
# 4
df['discount'] = df['discount'].fillna(0)
print(df['discount'])

21
4.0
0      5.0
1      4.0
2      4.0
3      5.0
4      4.0
      ...
198    4.0
199    4.0
200    4.0
201    4.0
202    4.0
Name: rating, Length: 203, dtype: float64
0      10.0
1      15.0
2       0.0
3      15.0
4      10.0
       ...
198     0.0
199    10.0
200    20.0
201    10.0
202     5.0
Name: discount, Length: 203, dtype: float64

### ✅ Task 10 — Removing Duplicates
1. Check how many **duplicate rows** exist in the DataFrame.
2. Display the duplicate rows.
3. Remove duplicates and store the clean DataFrame back into `df`.
4. Confirm the new shape.

In [103]:
# 1
duplicate_count = df.duplicated().sum()
print(duplicate_count)

# 2
duplicate_rows = df[df.duplicated(keep=False)]
print("\nDuplicate Rows:")
print(duplicate_rows)

# 3
df = df.drop_duplicates()

# 4
print(df.shape)

0

Duplicate Rows:
Empty DataFrame
Columns: [user_id, age, gender, occupation, zip_code]
Index: []
(943, 5)

### ✅ Task 11 — Renaming and Dropping Columns
1. Rename the column `unit_price` to `price_usd` and `customer_name` to `customer`.
2. Drop the column `order_id` from a **copy** of the DataFrame (do not modify `df`).
3. Reset the index of that copy and print it.

In [15]:
# Rename columns
df_renamed = df.rename(columns={
    "unit_price": "price_usd",
    "customer_name": "customer"
})

df_copy = df_renamed.drop(columns=["order_id"])

df_copy = df_copy.reset_index(drop=True)

print(df_copy)

                       order_date          customer          city region  \
0   2023-01-01 00:00:00.000000000    Karen Robinson   San Antonio  South
1   2023-01-02 19:53:58.190954773  Michael Williams       Houston  South
2   2023-01-04 15:47:56.381909547       Karen Moore        Dallas  South
3   2023-01-06 11:41:54.572864321    Michael Martin       Phoenix   West
4   2023-01-08 07:35:52.763819095  Jessica Williams   San Antonio  South
..                            ...               ...           ...    ...
198 2023-12-29 04:06:01.809045228      Robert Brown   Los Angeles   West
199 2023-12-31 00:00:00.000000000    Susan Robinson  Philadelphia   East
200 2023-01-10 03:29:50.954773869      Susan Thomas       Seattle   West
201 2023-02-12 01:41:18.391959799  Michael Robinson  Philadelphia   East
202 2023-05-21 20:15:40.703517588       Sarah Davis        Austin  South

        category       product  quantity  price_usd  discount    salesperson  \
0       Clothing        Jacket         1      89.99      10.0      David Lee
1           Food     Olive Oil         5      12.99      15.0      David Lee
2           Food     Olive Oil         7      12.99       0.0   Bob Martinez
3      Furniture          Desk         6     349.99      15.0      David Lee
4      Furniture  Office Chair         1     249.99      10.0     Emma Davis
..           ...           ...       ...        ...       ...            ...
198         Food           Tea         4       9.99       0.0  Alice Johnson
199     Clothing         Dress         6      69.99      10.0   Bob Martinez
200  Electronics        Laptop         5     999.99      20.0     Emma Davis
201    Furniture     Bookshelf         1     149.99      10.0     Emma Davis
202         Food           Tea         2       9.99       5.0   Bob Martinez

     rating
0       5.0
1       4.0
2       4.0
3       5.0
4       4.0
..      ...
198     4.0
199     4.0
200     4.0
201     4.0
202     4.0

[203 rows x 11 columns]

### ✅ Task 12 — `loc` and `iloc`
Using the original `df`:
1. Use **`iloc`** to select rows 10 to 20 and the first 4 columns.
2. Use **`loc`** to select all rows where `region == 'West'`, showing only `city`, `product`, and `unit_price`.
3. Use **`loc`** to update the `discount` of row at index `0` to `50`.

In [18]:
# 1
df.iloc[10:21, 0:4]

# 2 
df.loc[df["region"] == "West", ["city", "product", "unit_price"]]

# 3 
df.loc[0, "discount"] = 50

# 4
print(df.loc[0])

order_id                    ORD-1000
order_date       2023-01-01 00:00:00
customer_name         Karen Robinson
city                     San Antonio
region                         South
category                    Clothing
product                       Jacket
quantity                           1
unit_price                     89.99
discount                        50.0
salesperson                David Lee
rating                           5.0
Name: 0, dtype: object